SELECT A.CAR_ID, A.CAR_TYPE, ROUND(DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B
ON A.CAR_ID = B.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS C
ON A.CAR_TYPE = C.CAR_TYPE
WHERE (A.CAR_TYPE = '세단' OR A.CAR_TYPE = 'SUV') AND C.DURATION_TYPE = '30일 이상'
GROUP BY A.CAR_ID
HAVING FEE >= 500000 AND FEE < 2000000 AND A.CAR_ID NOT IN (SELECT CAR_ID 
                 FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                 WHERE (START_DATE BETWEEN '2022-11-01' AND '2022-11-30') 
                                                            OR (END_DATE BETWEEN '2022-11-01' AND '2022-11-30')
                                                            OR (START_DATE <= '2022-11-01' AND END_DATE >= '2022-11-30')                                            
                )
ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC