-- 코드를 작성해주세요
-- 코드를 작성해주세요
SELECT A.ID,A.EMAIL,A.FIRST_NAME,A.LAST_NAME
FROM DEVELOPERS A
WHERE (A.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) OR (A.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) 
ORDER BY A.ID ASC